// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_O2IKxorDgg3SykE8mIdyVlpYSOYuC4',
    appId: '1:60344304540:web:f39549b928edf6d52d7e59',
    messagingSenderId: '60344304540',
    projectId: 'easy-rent-54cd4',
    authDomain: 'easy-rent-54cd4.firebaseapp.com',
    storageBucket: 'easy-rent-54cd4.firebasestorage.app',
    measurementId: 'G-BLM5KC5DVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXEIPuWu2Z0J7U4tDpqC_t45Y-f_T7mEk',
    appId: '1:60344304540:android:4511f9183c3a39d02d7e59',
    messagingSenderId: '60344304540',
    projectId: 'easy-rent-54cd4',
    storageBucket: 'easy-rent-54cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkqdPtuGFV4ynai_YillP_tU1NQ1EMOJ4',
    appId: '1:60344304540:ios:3be0b1b920ab54c62d7e59',
    messagingSenderId: '60344304540',
    projectId: 'easy-rent-54cd4',
    storageBucket: 'easy-rent-54cd4.firebasestorage.app',
    iosClientId:
        '60344304540-uq690v4qgt5ic0iovi9q3po2ch2u5ak3.apps.googleusercontent.com',
    iosBundleId: 'com.daki.baillan',
  );
}
